### ISSUE TITLE
unable to import tensorflow-lattice in Windows 7

### ISSUE THREAD

**Issue by LubaOrlovsky** [tensorflow/lattice#8]
Hi,
I have installed the package through Anaconda and then I've tried to import it through Spyder. This is the error i receive:
```
import tensorflow_lattice
Traceback (most recent call last):

  File "<ipython-input-21-fdc786e468a5>", line 1, in <module>
    import tensorflow_lattice

  File "C:\Users\lubao\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_lattice\__init__.py", line 33, in <module>
    from tensorflow_lattice.python.estimators.calibrated import input_calibration_layer_from_hparams

  File "C:\Users\lubao\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_lattice\python\estimators\calibrated.py", line 23, in <module>
    from tensorflow_lattice.python.lib import pwl_calibration_layers

  File "C:\Users\lubao\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_lattice\python\lib\pwl_calibration_layers.py", line 31, in <module>
    from tensorflow_lattice.python.ops import pwl_calibration_ops

  File "C:\Users\lubao\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_lattice\python\ops\pwl_calibration_ops.py", line 42, in <module>
    '../../cc/ops/_pwl_calibration_ops.so'))

  File "C:\Users\lubao\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\load_library.py", line 64, in load_op_library
    # that are no longer needed.

NotFoundError: C:\Users\lubao\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_lattice\python\ops\..\..\cc\ops\_pwl_calibration_ops.so not found
```
Any help is greatly appreciated
Thanks,
Luba

**Comment by si-you** [comment]
Hi there. Currently we only support linux and macosx. Could you try it in linux?

Thank you!

**Comment by LubaOrlovsky** [comment]
Hi, thanks! It works on linux indeed. Any plans for Windows support?

**Comment by AbdalaDiasse** [comment]
I have also tried on windows it got the same error . Thank your @si-you for such a clarification.

**Comment by evan-magnusson** [comment]
I have the same error.  Would be nice if this was clear from the install page, before I reverted to python 3.6 to get tf 1.11 to install this.
